web:
  image: quay.io/spesnova/docker-example-rails
  command: bundle exec puma -C config/puma.rb -b unix:///app/tmp/puma.sock
  volumes:
    - /app
  ports:
    - 3000
  links:
    - db
  environment:
    - RACK_ENV=production
    - RAILS_ENV=production
    - RAILS_SERVE_STATIC_FILES=true
    - MIN_THREADS=1
    - MAX_THREADS=1
    - DATABASE_HOST=db
    - DATABASE_PORT=5432
    - DATABASE_USER=hello
    - DATABASE_PASSWORD=world
    - SECRET_KEY_BASE=450a851180c712e6a7ba6f4ab4a9624caddfc02d842eef3315cc47f9b0a16ef3cb5e5b68184d998604076a05d32d108b465f7bfe23623222690be720c7bfd39c
db:
  image: postgres:9.4.0
  ports:
    - 5432
  environment:
    - POSTGRES_USER=hello
    - POSTGRES_PASSWORD=world
nginx:
  build: .
  ports:
    - 80:80
  volumes_from:
     - web
