#!/bin/bash
#
# Usage: script/run
# Description: run Nginx container
#

set -e

IMAGE="quay.io/spesnova/docker-example-nginx"
CONTAINER="docker-example-nginx"

docker kill "${CONTAINER}" > /dev/null 2>&1 || true
docker rm   "${CONTAINER}" > /dev/null 2>&1 || true

docker run \
  -it \
  --rm \
  --name "${CONTAINER}" \
  -e SERVERNAME="hello" \
  -p 80:80 \
  -p 8090:8090 \
  -v /etc/nginx/switch:/etc/nginx/switch:ro \
  --net=host \
  "${IMAGE}" \
  $@
