#!/bin/bash
#
# Usage: script/test
#

set -e

export COMPOSE_PROJECT_NAME=test

compose build
compose stop
compose rm --force
compose up -d db
sleep 4
compose run --rm web rake db:create db:migrate
compose up -d
sleep 2

docker kill infrataster > /dev/null 2>&1 || true
docker rm   infrataster > /dev/null 2>&1 || true
docker run \
  --rm \
  --name infrataster \
  -v $PWD/test/feature/spec:/test/spec \
  -e TARGET_IP=127.0.0.1 \
  --net host \
  quay.io/wantedly/infrataster:latest
